version: 2.1

orbs:
  discord: antonioned/discord@0.1.0

jobs:
  test:
    docker:
      - image: cimg/go:1.19.4

    working_directory: ~/repo

    steps:
      - checkout

      - run: go get

      - run: go test -cover -v ./...

      - run: go build ./handler.go

      - discord/status:
          fail_only: true
          failure_message: "Triggered User: **${CIRCLE_USERNAME}**\\nBranch: **${CIRCLE_BRANCH}**\\n\\nCircleCI テストに失敗しました。 JOB: **$CIRCLE_JOB**"
          webhook: "${DISCORD_WEBHOOK}"

workflows:
  version: 2
  ci:
    jobs:
      - test:
          context: kazuhito_m-products
